
#include "Utils/Structs/ForSkanData.h"


TMap<EForSkanType, TArray<FString>> FForSkanData::ForSkanPotentialStrings = {
    {EForSkanType::Bad, {
        TEXT("Post wrist size or gtfo (no manlets allowed)."),
        TEXT("JFL, just saw a 5'7 guy with a gf. Society is finished."),
        TEXT("Bro… why is my eye area melting???"),
        TEXT("life starts at 7 PSL"),
        TEXT("Don't even try if you're sub6'6"),
        TEXT("AHAHAHAH"),
        TEXT("DNR a molecule"),
        TEXT("I hate this world"),
        TEXT("fuck love"),
        TEXT("I'm going ER any moment now"),
        TEXT("I’ve been lifting for 3 years, still look like a manlet. It’s over."),
        TEXT("Transition"),
        TEXT("Abs don’t matter when you're still a framelet lmao."),
        TEXT("I’ve been working on my deadlift, but I still look like a walking disappointment."),
        TEXT("Hit a PR today. Don’t care. Still invisible. Why not rope?"),
        TEXT("You will transform your body, but it won’t matter. No one will care. Face (all genetic) is and always will be law."),
        TEXT("I can’t escape the feeling that no matter what I do, nothing will change."),
        TEXT("No matter how much I bulk, I still look like a fucking twig."),
        TEXT("I’ve been on a bulk for 6 months. Now I’m just fat and ugly. Hardmaxxers were right."),
        TEXT("Tried fillers. Looked in the mirror. Still a freak."),
        TEXT("Leanmaxxed to 3% bodyfat and bones still look subhuman, fuck my genetics"),
        TEXT("I’ve put in the work, tried every method. But at the end of the day, I’ll always be unattractive."),
        TEXT("No gym for my face"),
        TEXT("No amount of grooming or mewing will ever fix my disgusting features."),
        TEXT("You cope all these hours in the gym, but your face is still JFL.")
    }},

    {EForSkanType::Good, {
        TEXT("Subhuman no more – finally hit neutral canthal tilt."),
        TEXT("mogs Gandy"),
        TEXT("9 PSL god"),
        TEXT("holy frame"),
        TEXT("Unknown Slayer"),
        TEXT("Feeling my body grow stronger, but my mind is growing stronger with it."),
        TEXT("I FEEL GREAT TODAY"),
        TEXT("IT'S HAPPENING"),
        TEXT("Feeling the VRIL, feeling the ascension rn."),
        TEXT("I’ve learned that strength isn’t just about muscles. It’s about being mentally tough, too."),
        TEXT("Form improved, posture improved, mindset improved. This is the trifecta."),
        TEXT("The weights aren’t heavy anymore. My mind is lighter."),
        TEXT("Hitting PRs, but I’m more proud of my consistency. It’s the journey."),
        TEXT("You will see progress, even if it’s slow. Every small change is a victory."),
        TEXT("you're gonna ascend soon ngl, keep grinding bhai"),
        TEXT("You will feel more in control of your life and your choices. This is your journey."),
        TEXT("You will unlock your true potential, piece by piece, rep by rep."),
        TEXT("Your mind, body, and soul will sync to actualize your true potential soon, I see your Chad genetics realized any moment now."),
        TEXT("Keep grinding and you'll figure it out brocel"),
        TEXT("Just give it time and stay focused."),
        TEXT("The more I PR, the less urge to go ER")
    }},

    {EForSkanType::Crazy, {
        TEXT("AI girlfriends will be our salvation (GPTWaifu 2.0 thread)"),
        TEXT("My skull is 0.3 SD too small, should I just ascend via car crash?"),
        TEXT("Why do babies mog me???"),
        TEXT("Life ends at Kindergarten"),
        TEXT("Being a 16 inch bidelt BWC/BBC sissy femboy is IDEAL in 2025"),
        TEXT("Just did a skull measurement, my life is officially over."),
        TEXT("The moonlight mogs me, I can’t go outside at night anymore."),
        TEXT("Gandy is a government psyop to make us feel inferior."),
        TEXT("Chico aka Fransiscso (((Lachowski))) is just another industry plant"),
        TEXT("Took 100mg of Viagra and just stared at myself in the mirror, contemplating existence."),
        TEXT("Bro I think my skull is SHRINKING."),
        TEXT("Elites are hoarding the perfect jawline genes—we were NEVER meant to ascend."),
        TEXT("Squatted so deep I saw my ancestors."),
        TEXT("The fluoride in tap water isn’t to dumb us down, it’s to weaken our zygos so we stay ugly."),
        TEXT("I lifted, but my arms didn’t move."),
        TEXT("My veins are writing messages I can't read."),
        TEXT("The gym never existed."),
        TEXT("My body is trying to escape itself."),
        TEXT("DAE put an olympic weight clamp on their dick to girthmax? Been seeing good results so far, concerning dark spots be damned."),
        TEXT("Someone else is doing my sets."),
        TEXT("I'm sorry."),
        TEXT("I'm HORNY"),
        TEXT("Got so shredded that my shadow stopped matching my movements.")
    }},

    {EForSkanType::Mixed, {
        TEXT("Just give it time and stay focused."),
        TEXT("Keep grinding and you'll figure it out brocel"),
        TEXT("Post wrist size or gtfo (no manlets allowed)."),
        TEXT("Feeling the VRIL, feeling the ascension rn."),
        TEXT("Why do babies mog me???"),
        TEXT("Hit a PR today. Don’t care. Still invisible. Why not rope?"),
        TEXT("You're gonna ascend soon ngl, keep grinding bhai"),
        TEXT("Squatted so deep I saw my ancestors."),
        TEXT("DNR a molecule"),
        TEXT("The gym never existed."),
        TEXT("Subhuman no more – finally hit neutral canthal tilt."),
        TEXT("JFL, just saw a 5'7 guy with a gf. Society is finished."),
        TEXT("The more I PR, the less urge to go ER")
    }}
};
